// Code generated by gromer. DO NOT EDIT.
package main

import (
	c "context"
	"embed"
	"net/http"
	"os"

	"github.com/apex/gateway/v2"
	"github.com/gorilla/mux"
	"github.com/pyros2097/gromer"
	"github.com/rs/zerolog/log"
	"gocloud.dev/server"

	"github.com/pyros2097/gromer/example/context"
	"github.com/pyros2097/gromer/example/pages/about"
	"github.com/pyros2097/gromer/example/pages/api/todos/_todoId_"
	"github.com/pyros2097/gromer/example/pages/api/todos"
	"github.com/pyros2097/gromer/example/pages"
	
)

//go:embed assets/*
var assetsFS embed.FS

func main() {
	isLambda := os.Getenv("_LAMBDA_SERVER_PORT") != ""
	r := mux.NewRouter()
	r.NotFoundHandler = http.HandlerFunc(notFound)
	r.PathPrefix("/assets/").Handler(wrapCache(http.FileServer(http.FS(assetsFS))))
	handle(r, "GET", "/api", gromer.ApiExplorer(apiDefinitions()))
	handle(r, "GET", "/about", about.GET)
	handle(r, "DELETE", "/api/todos/{todoId}", todos_todoId_.DELETE)
	handle(r, "GET", "/api/todos/{todoId}", todos_todoId_.GET)
	handle(r, "PUT", "/api/todos/{todoId}", todos_todoId_.PUT)
	handle(r, "GET", "/api/todos", todos.GET)
	handle(r, "POST", "/api/todos", todos.POST)
	handle(r, "GET", "/", pages.GET)
	
	if !isLambda {
		println("http server listening on http://localhost:3000")
		srv := server.New(r, nil)
		if err := srv.ListenAndServe(":3000"); err != nil {
			log.Fatal().Stack().Err(err).Msg("failed to listen")
		}
	} else {
		log.Print("running in lambda mode")
		if err := gateway.ListenAndServe(":3000", r); err != nil {
			log.Fatal().Stack().Err(err).Msg("failed to listen")
		}
	}
}

func wrapCache(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "public, max-age=2592000")
		h.ServeHTTP(w, r)
	})
}

func notFound(w http.ResponseWriter, r *http.Request) {
	gromer.LogReq(404, r)
}

func handle(router *mux.Router, method, route string, h interface{}) {
	router.HandleFunc(route, func(w http.ResponseWriter, r *http.Request) {
		var status int
		defer func() {
			gromer.LogReq(status, r)
		}()
		ctx, err := context.WithContext(c.WithValue(
			c.WithValue(
				c.WithValue(r.Context(), "assetsFS", assetsFS),
					"url", r.URL),
			"header", r.Header))
		if err != nil {
			gromer.RespondError(w, 500, err)
			return
		}
		status, err = gromer.PerformRequest(route, h, ctx, w, r)
		if err != nil {
			log.Error().Stack().Err(err).Msg("")
		}
	}).Methods(method)
}

func apiDefinitions() []gromer.ApiDefinition {
	return []gromer.ApiDefinition{
		
		{
			Method: "DELETE",
			Path: "/api/todos/{todoId}",
			PathParams: []string{ "todoId",  },
		},
		{
			Method: "GET",
			Path: "/api/todos/{todoId}",
			PathParams: []string{ "todoId",  },
		},
		{
			Method: "PUT",
			Path: "/api/todos/{todoId}",
			PathParams: []string{ "todoId",  },
		},
		{
			Method: "GET",
			Path: "/api/todos",
			PathParams: []string{  },
		},
		{
			Method: "POST",
			Path: "/api/todos",
			PathParams: []string{  },
		},
	}
}
