FROM golang:1.18-buster AS build

WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY ./ ./
RUN cd _example && go build -o /out

FROM gcr.io/distroless/base:latest

WORKDIR /
COPY --from=build /out /out
ENTRYPOINT ["/out"]